### PR TITLE
Refactor to share course enrollments components and data layer

### PR DESCRIPTION
**Pull request by adamstankiewicz**
This PR abstracts out the logic around fetching course enrollments into a shared component across both Masters and Enterprise as the relevant UI and API responses are nearly identical.

In more detail, this PR addresses the following:
* Upgrades @edx/paragon to latest version to take advantage of the refactor `Collapsible` component.
* Moves the logic around fetching course enrollments into a new `common/course-enrollments` folder component. This folder & components are now responsible for everything related to course enrollments as it relates to displaying the course sections and course cards.
  * This includes moving the `CourseSection` component and `course-cards` folder into this new `course-enrollments` directory.
* The `CourseEnrollments` component is agnostic to whether it's rendering program course enrollments or enterprise course enrollments, except that it determines which service endpoint to use to fetch course enrollments (the one for programs, or the one for enterprise).
* Moved the logic for grouping course runs by status into `selectors.js` file, taking advantage of the `reselect` library.
  * This is good as the course runs data will already be transformed with the necessary fields for rendering the course enrollments UI before it reaches the `CourseEnrollments` rendering.
* Noticed a bug in the saving logic of the email settings, where the "Save" button remained disabled after performing a successful save, and then changing the form again (which should allow the "Save" button to be clicked again).
  * There's a test related to email settings that's now failing, though so still need to confirm that logic and/or update the test.
* Converts API response fields to camelCase before it reaches the component (more in-line with JS syntax / best practices).

A test is currently failing due to the use of `camelcase-keys`, so I need to look into that or if there's a better way to convert snake_case API response field names to camelCase (the Payment MFE seems to have some prior art on this, but not in a reusable way; could potentially copy/paste their relevant code to do the snake-to-camel conversion). Bringing this issue up at the FedX meeting later today (8/22).

### CODE REVIEW

**Comment by douglashall** [comment]
Interesting. I was looking to use camelcase-keys as well in my PR.

**Comment by adamstankiewicz** [comment]
> Do you feel like you are blocked on the camelcase-keys thing or are you just going to switch to copy/paste of the custom code?

Chatted about that in the FedX meeting earlier. Going to do some copy/paste magic from the Payment MFE. Turns out the same utility methods (at last around the camelCase) are being copy/pasted in 4 MFEs right now. There is some proposed work to abstract those types of things into an @edx/frontend-utils package that would be an ideal home for the camelCase utility functions.

I'm going to copy/paste into a `src/common/utils.js` file with a comment explaining that we'll want to begin using @edx/frontend-utils once it's available.

**Comment by adamstankiewicz** [comment]
Still trying to resolve the failing test around email settings. I might actually remove my relevant changes to the `EmailSettingsModal` in this PR as it's not directly relevant, and so we can get this over the line sooner. Of course, would open a new PR for the email settings bug fix I found, including fixing that failing test.

**Comment by adamstankiewicz** [comment]
> Still trying to resolve the failing test around email settings. I might actually remove my relevant changes to the `EmailSettingsModal` in this PR as it's not directly relevant, and so we can get this over the line sooner. Of course, would open a new PR for the email settings bug fix I found, including fixing that failing test.

Was able to get this issue resolved in this PR as well.

**Pull request merged**
