### PR TITLE
Move provider slug from config to environment

### PR DESCRIPTION
**Pull request by Tj-Tracy**
This will eventually be needed for deployment, and is needed right now
for sandbox testing.

### CODE REVIEW

**Comment by tuchfarber** [comment]
If we're adding a value to .env.development, do we have to add it to the WHITELIST of the env plugin? Not sure how all that links together yet?

**Comment by Tj-Tracy** [comment]
I'm actually not sure exactly what that is, but the redirect url is created properly without it.

according to gatsby docs, the GATSBY_ prefix is only needed for OS Env variables, and is not needed for .env.* files:

https://www.gatsbyjs.org/docs/environment-variables/

> In addition to these Project Environment Variables defined in .env.* files, you could also define OS Env Vars. OS Env Vars which are prefixed with GATSBY_ will become available in browser JavaScript.

...which is believe is what the whitelist is for? @adamstankiewicz may know.

**Comment by adamstankiewicz** [comment]
> I'm actually not sure exactly what that is, but the redirect url is created properly without it.
> 
> according to gatsby docs, the GATSBY_ prefix is only needed for OS Env variables, and is not needed for .env.* files:
> 
> https://www.gatsbyjs.org/docs/environment-variables/
> 
> > In addition to these Project Environment Variables defined in .env.* files, you could also define OS Env Vars. OS Env Vars which are prefixed with GATSBY_ will become available in browser JavaScript.
> 
> ...which is believe is what the whitelist is for? @adamstankiewicz may know.

Correct. That is what the whitelist plugin is for. It removes the need for those environment variables to be prefixed by `GATSBY_` to be accessible on the client.

**Comment by adamstankiewicz** [comment]
> If we're adding a value to .env.development, do we have to add it to the WHITELIST of the env plugin? Not sure how all that links together yet.
> 
> https://github.com/edx/frontend-app-learner-portal/blob/990e04165e31fa5dc193dc95ed42f63b88c91b6d/gatsby-config.js#L36

If the environment variable needs to be accessible on the client at runtime, then we should opt for putting it in the whitelisted environment variables. If it's only read at build time, then it does not need to be in the whitelist.

**Comment by Tj-Tracy** [comment]
The `SAML_IDP_SLUG` right now is only used in the `gatsby-config`, and is not needed client side as the metadata is created at build time -- therefore the variable does not need to be whitelisted.

**Comment by tuchfarber** [comment]
Just to clarify the conversation above:
I'm assuming `SAML_IDP_SLUG` will be different per deployment, and therefore would need to be passed in as an env var in the build process. So we will need it to be whitelisted when we're at that state.

It's fine without for now/testing, but we'll need it when we go live. 

If it's not different per deployment, then it's not an issue at all.

**Pull request closed without merging**
